# Generated by Django 5.2.1 on 2025-11-09 18:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter', models.CharField(choices=[('electricity', 'Electricity'), ('gas', 'Gas')], max_length=20, unique=True)),
                ('starting_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tariff', models.DecimalField(decimal_places=4, default=0.2, help_text='Currency per unit (e.g. £ per kWh)', max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='TopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('meter', models.CharField(choices=[('electricity', 'Electricity'), ('gas', 'Gas')], max_length=11)),
                ('credit', models.DecimalField(decimal_places=2, help_text='Top up amount £', max_digits=10)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UtilityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, unique=True)),
                ('electricity', models.FloatField(blank=True, null=True)),
                ('gas', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
