# Generated by Django 5.2.1 on 2025-11-14 23:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('meter', models.CharField(choices=[('electricity', 'Electricity'), ('gas', 'Gas')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Currency amount added (e.g. £)', max_digits=10)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UtilityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('electricity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
